feat: Upgrade to Spring Boot 3.5.14 (#142)
* feat: Spring Boot upgrade to 3.3.13: initial changes of dependencies and source files. Bump atp libraries versions to ones already upgraded to Spring Boot 3.3.13. Bump dependencies: undertow to 2.3.21.Final, kotlin to 1.9.25, jackson to 2.18.6. Jakarta.jms:jakarta.jms-api:3.1.0 is added instead of javax.jms:jms-api, springfox dependencies are removed, org.springdoc:springdoc-openapi-starter-webmvc-ui:2.8.16 is added instead.

* fix: IllegalClassException is replaced to IllegalArgumentException. Also: Some code check warns are fixed.

* fix(deps): Bump dependencies: activemq to 6.1.6, xnio to 3.8.16.Final, aspectj to 1.9.24, camel to 4.14.5, cxf to 4.1.4. Remove/replace relocated dependencies camel-http4 and camel-netty4.

* build: Plugin management is fixed for maven-compiler-plugin.

* build: openapi-generator-maven-plugin: version is changed to 7.9.0, configuration is upgraded for Spring Boot 3.3.13 and optimized.

* fix: BigInteger vs. Serializable types mismatch is fixed while using UniqueIdGenerator.generate().

* fix: EventTriggerSwitcherFactoryTest, EventTriggerSwitcherTest: incomplete migration from Junit4 to Junit5 is completed.

* fix: Pact-tests (consumer side) are fixed. Bump au.com.dius.pact.provider and au.com.dius.pact.consumer dependencies to 4.6.15.

* fix: Some tests are migrated from Junit4 to Junit5 and fixed.

* feat: Usages of keycloak are replaced to Jwt. Keycloak dependency is removed.

* fix: CommonsMultipartResolver bean is replaced with MultipartResolver. application.properties: spring.servlet.multipart config properties are changed.

* fix: Obsolete AbstractWebSocketMessageBrokerConfigurer is replaced to WebSocketMessageBrokerConfigurer.

* fix: Javers usages are migrated from 6.x to 7.9.0.

* feat: Camel migration to 4.14.5, Cxf migration to 4.1.4: Http, Rest,Soap, Jms, Cli, Ss7 modules are migrated.

* fix: Pact tests (consumer side) are fixed: custom OffsetDateTimeAdapter implemented and registered for Gson.

* fix: Pact tests (producer side) are fixed: urls to json files in @PactUrl annotations are fixed.

* fix: SqlOutboundTransport is fixed. Cassandra connections and query results processing are rewritten. com.datastax.cassandra:cassandra-driver-*:3.7.1 dependencies are replaced to com.datastax.oss:java-driver-core:4.17.0. Bump commons-dbcp2 version to 2.12.0. Also: commons-logging is excluded to avoid loggers conflict.

* fix: Ldap Outbound transport is fixed.

* fix: Transport tests are fixed.

* fix: Fix of VelocityTemplateEngineTest tests. Some Velocity Tools are turned off to avoid using of javax/servlet package classes.

* fix: Fix of object id types (change from Object to BigInteger).

* fix(security): Bump dependencies: sshd-core to 2.9.2, tomcat-embed to 10.1.52, org.apache.poi to 3.17, org.jsoup:jsoup to 1.14.2, hazelcast to 5.2.5, angus-mail to 2.0.4. Bump APK package: zlib to 1.3.2-r0.

* fix(deps): Bump dependency version: querydsl to 5.1.0:jakarta. Remove uk.co.jemos.podam:podam. Improve hazelcast dependencies management.

* fix: Rename SPRING_PROFILES property to ACTIVE_PROFILES_SPRING.

* fix: Dependency management: Tomcat-embed dependencies are excluded from atp-integration dep.

* fix: Velocity Tools: some tools are temporarily excluded from Engine init, to avoid ClassNotFound errors during application start.

* fix: Config setting is added to instruct Hibernate to transform xml mapping on the fly.

* fix(deps): Direct dependency to org.hibernate.orm:hibernate-core:6.5.3.Final is added.

* fix(deps): Dependency com.hazelcast:hazelcast-hibernate6:2.3.1 is added to ensure Hazelcast + Hibernate work together. Hibernate properties are renamed. Also: commons-logging dependency is excluded to avoid loggers conflicts.

* fix(deps): Transitive org.antlr:antlr-runtime dependency is excluded to avoid ATN versions conflict. Bump org.antlr:antlr4-runtime version to 4.13.0.

* fix: Technical debt: DynamicHttpClientConfigurer and PreconfiguredHttpClientHolder are migrated to httpclient5.

* fix(deps): Bump spring-kafka to 3.3.3.

* fix(deps): Align io.github.openfeign version with Spring Boot managed (13.5).

* fix: application.properties: Fix datasource and hibernate properties.

* fix: Add javax.cache:cache-api:1.1.1 and org.hibernate.orm:hibernate-jcache:6.5.3.Final dependency to use Hibernate 2nd-level cache with Hazelcast provider via JCache.

* fix(security): Bump openjdk to 21.0.11, bump APK packages: libpng to 1.6.57-r0, libcrypto3 to 3.5.6-r0, libssl3 to 3.5.6-r0, musl to 1.2.5-r23, musl-utils to 1.2.5-r23, sops to 3.11.0-r5, xz-libs to 5.8.3-r0.

* feat: Spring Boot upgrade to 3.5.14: Initial changes by OpenRewrite plugin. Bump atp libraries to ones already upgraded to SB 3.5.x. 

* fix: Fix methods according to modern API.

* fix(deps): Bump bouncycastle to 1.84, logback to 1.5.32, netty to 4.1.132.Final, camel to 4.14.6. Direct dependencies hibernate-jcache and javax.cache:cache-api:1.1.1 are added.

* fix: CacheAutoConfiguration is excluded from Spring Boot application.

* fix(tests): Turn off sending Pact metrics in pact tests (provider side) to avoid ClassNotFound errors due to httpclient5 versions mismatch (5.4.4 used in the project vs. 5.3.x used in Pact library 4.6.15).

* fix(tests): MockBean is replaced to MockitoBean in pact tests.

* fix(deps): Exclude com.vaadin.external.google:android-json from spring-boot-starter-test, to avoid json parsers jar hell.

* build: Bump maven-surefire-plugin to 3.2.5. Turn off sending of Pact metrics in pact tests (consumer side).

* refactor: Usages of org.assertj.core.util package are removed.

* fix(tests): Unit-tests for SqlOutboundTransport are implemented. Required mockito (5.23.0) and Junit (5.12.2) dependencies are added.

* feat: change versions atp-auth to 2.0.0; atp-common to 1.0.0; atp-integration to 1.0.0; atp-multitenancy to 1.0.0; atp-ei.lib to 1.0.0; atp-crypt to 1.0.0.

* feat: Change Apacha Camel version to 4.18.0; 

* feat: Exclude org.apache.cxf:cxf-rt-ws-security;

* fix(deps): Bump Apache POI to 5.2.5.

* feat: upgrade class AuthTokenProvider for new spring security; add property spring.cloud.openfeign.httpclient.disable-ssl-validation,

* feat: change default value for feign.atp.reports.name; add property 'management.tracing.enabled';

* feat: add property 'spring.cloud.openfeign.httpclient.hc5.enabled' and 'spring.cloud.openfeign.okhttp.enabled' to application.properties;

* feat: add exclude HazelcastAutoConfiguration.class

* feat: add property 'eureka.client' to application.properties; remove org.hibernate.orm:hibernate-jcache,

* feat: Remove servlets - soap, diameter, rest because of unused; commented class CxfConfiguration;

* feat: add property 'spring.sql.init.mode' to application.properties; refactor some classe.

* fix: Fix id/naturalId processing for DataSetLists, RemoteDataSetLists, Datasets and VisibilityAreas. Unit tests are added.

* fix: Fix ID processing while UI object creation from storable object. Add Unit tests for DatasetController. Also: Fix TcContext ID calculation in case error is faced while preparing of executeStep action execution.

* feat: Exclude unused dependency from modules: mockingbird-transport-cli, mockingbird-transport-sql;

* fix: Fix Cassandra session creation. Rewrite Cassandra query execution (avoid using Camel).

* fix(tests): Add Unit test for different parsing rule types. 

* feat: fix cast long to biginteger for stub request;

* fix: Remove cglib dependency. 

* fix(tests): Add AtpCallchainExecutor Unit Tests.

* feat: add dependency com.oracle.database.jdbc:ojdbc11; add module java.base/sun.util.calendar; change httpclient5 version to 5.5.2; httpcore5 version to 5.3.6;

* feat: fix parse xml message get in from stub; 

* feat: Fix error in outbound Soap transport (NoClassDefFoundError: org/apache/camel/component/cxf/common/CxfBinding), add org.apache.camel:camel-cxf-soap

* fix: Fix Camel response processing in SqlOutboundTransport, CLI-, Http- and Ldap- Outbound transports.

* fix: Fix caching and HttpComponent processing in HTTPOutboundTransport.

* feat: fix error for kafka transport; change org.apache.kafka:kafka-clients version to 3.9.2;

* fix: Fix Camel components processing.

* fix: Fix ServerConfigurationController#setupOutbound to avoid Optimistic Locking exception.

* feat: add some property to disable redirects in REST Outbound transport;

* fix: Mark projectSettingsService bean as @Primary. 

* feat: fix warning in logback;

* fix(docs): Fix markdown errors.

* fix(deps): Bump diameter-library to 3.0.0, ss7 to 2.0.0, configuration-dataset-excel-library to 4.0.0.

* fix(deps): Bump itf-core to 5.0.0, Undertow to 2.3.24.Final, gson to 2.13.2, Tomcat-embed to 10.1.54. Remove outdated org.jvnet.jax-ws-commons.spring:jaxws-spring:1.9.

* fix(deps): Fix Apache Velocity dependencies.

---------

Co-authored-by: dmch1019 <dmitrii.churbanov@netcracker.com>
Co-authored-by: kagw95 <aleksandr.kapustin@netcracker.com>